### ISSUE TITLE
Non-numeric value encountered

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-urls#10]
As reported [here](https://wordpress.org/support/topic/receiving-a-php-warning/), this warning is logged when a link is visited and the visit count increments:

```
PHP Warning: A non-numeric value encountered in /home/site/public_html/
wp-content/plugins/simple-urls/plugin.php on line 203\
```

I tested with PHP 7.2.5 and can reproduce this.

PR at https://github.com/copyblogger/simple-urls/pull/11.

**Comment by marksabbath** [comment]
Closed by #11
