### ISSUE TITLE
Expose Simple URL post type to REST API

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-urls#12]
As reported at https://wordpress.org/support/topic/not-showing-in-wp-5-block-editor-link-suggestions/, Simple URL links do not appear in the URL prompt for the Block Editor when adding a link to paragraph text:

<img width="473" alt="screenshot 2019-03-01 at 10 50 46" src="https://user-images.githubusercontent.com/647669/53630234-e6734200-3c0f-11e9-8054-eb4555c5004d.png">

Adding `'show_in_rest'  => true,` to `register_post_type` fixes this:

<img width="525" alt="screenshot 2019-03-01 at 10 51 42" src="https://user-images.githubusercontent.com/647669/53630319-14f11d00-3c10-11e9-80a2-524e081bd795.png">

Pull request incoming.

**Comment by marksabbath** [comment]
Closed by https://github.com/studiopress/simple-urls/pull/13
