### ISSUE TITLE
Customers report redirects fail, return to wp-admin

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-urls#18]
Several customers report issues with redirects returning 404s or redirecting to the homepage after the 0.9.8 update.

https://wordpress.org/support/topic/error-404-after-update-2/

This appears to be caused by the switch from `wp_redirect` to `wp_safe_redirect`, and attempting to whitelist the redirect URLs via `allowed_redirect_hosts`.

As the query to fetch URLs to whitelist does not specify `posts_per_page`, it looks like the plugin is only whitelisting a small subset of redirect URL hosts (because WP_Query will be limited by the site's Settings → Reading → “Blog pages show at most” value):

https://github.com/studiopress/simple-urls/blob/def6137485187546cee1120359f275e738e7df24/includes/class-simple-urls.php#L157-L161

I've submitted two potential fixes for this:

1. (Preferred) drop `wp_safe_redirect`, as it seems to serve no security benefit when we're whitelisting the URL the user has entered via the admin area: https://github.com/studiopress/simple-urls/pull/16
2. Filter `allowed_redirect_hosts` during the actual redirect, and allow only the host being redirected to, instead of attempting to whitelist all Simple URL redirect hosts on plugin initialization: https://github.com/studiopress/simple-urls/pull/17 (However, I do not see the security benefit in whitelisting a filterable set of URLs entered by the admin user.)

**Comment by JiveDig** [comment]
Wow what a find. Thanks for the diligence here yall!
