### ISSUE TITLE
Option to change 'go' prefix

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-urls#8]
Customers would like an option to alter the 'go' prefix before simple URLs.

Ref: https://wordpress.org/support/topic/is-this-plugin-going-to-be-updated-ever?replies=2#post-8487686

**Comment by dreamwhisper** [comment]
There is a filter: https://github.com/copyblogger/simple-urls/commit/d0b9f3aae60de2377acef359507b5d422855c96e

But, we need to update the FAQ:

> = Can I change the URL structure to use something other than /go/ ??? =

> No, not without modifying the plugin.

**Comment by dreamwhisper** [comment]
Filter was documented in latest release [readme.txt](https://github.com/studiopress/simple-urls/blob/develop/readme.txt#L39-L45)
